title = "SIMPLE SCENE"
spp = 128
[cameras]
    [[cameras.camera]]
    origin = [278.0,273.0,-800.0]
    up = [0.0,1.0,0.0]
    lookat = [278.0,273.0,-790.0]
    fov = 45.0
    film_height = 400
    film_width = 400
    type = "pinhole"

    # [[cameras.camera]]
    # origin = [1.0,2.0,0.0]
    # up = [0.0,1.0,0.0]
    # lookat = [0.0,0.0,-1.0]
    # fov = 90.0
    # film_height = 400
    # film_width = 400
    # type = "pinhole"

    # [[cameras.camera]]
    # origin = [0.0,0.0,5.0]
    # up = [0.0,1.0,0.0]
    # lookat = [0.0,0.0,-1.0]
    # fov = 90.0
    # film_height = 400
    # film_width = 400
    # type = "pinhole"




[objects]
  [[objects.name]]
  name = "tall_box"
  [[objects.material]]
  name = "matte_white"
  type = "glass"
  albedo = [0.725,0.71,0.68]
  texture = "constant"
  [[objects.transform]]
  matrix4 = [1.0,0.0,0.0,0.0,
         0.0,1.0,0.0,0.0,
         0.0,0.0,1.0,0.0,
         0.0,0.0,0.0,1.0]
  [[objects.shape]]
  type="obj"
  path="tallbox.obj"


  
  [[objects.name]]
  name = "small_box"
  [[objects.material]]
  name = "matte_white"
  type = "matte"
  albedo = [0.725,0.71,0.68]
  texture = "constant"
  [[objects.transform]]
  matrix4 = [1.0,0.0,0.0,0.0,
        0.0,1.0,0.0,0.0,
        0.0,0.0,1.0,0.0,
        0.0,0.0,0.0,1.0]
  [[objects.shape]]
  type="obj"
  path="shortbox.obj"


   [[objects.name]]
   name = "left"
   [[objects.material]]
   name = "matte_red"
   type = "matte"
   albedo = [0.63,0.065,0.05]
   texture = "constant"
   [[objects.transform]]
   matrix4 = [1.0,0.0,0.0,0.0,
         0.0,1.0,0.0,0.0,
         0.0,0.0,1.0,0.0,
         0.0,0.0,0.0,1.0]
   [[objects.shape]]
   type="obj"
   path="left.obj"


 [[objects.name]]
 name = "right"
 [[objects.material]]
 name = "matte_green"
 type = "matte"
 albedo = [0.14,0.45,0.091]
 texture = "constant"
 [[objects.transform]]
 matrix4 = [1.0,0.0,0.0,0.0,
       0.0,1.0,0.0,0.0,
       0.0,0.0,1.0,0.0,
       0.0,0.0,0.0,1.0]
 [[objects.shape]]
 type="obj"
 path="right.obj"

  [[objects.name]]
  name = "floor"
  [[objects.material]]
  name = "matte_white"
  type = "matte"
  albedo = [0.725,0.71,0.68]
  texture = "constant"
  [[objects.transform]]
  matrix4 = [1.0,0.0,0.0,0.0,
        0.0,1.0,0.0,0.0,
        0.0,0.0,1.0,0.0,
        0.0,0.0,0.0,1.0]
  [[objects.shape]]
  type="obj"
  path="floor.obj"

  [[objects.name]]
  name = "light"
  [[objects.material]]
  name = "matte_light"
  type = "matte"
  albedo = [0.65,0.65,0.65]
  emission = [47.8,38.6,31.1]
  texture = "constant"
  [[objects.transform]]
  matrix4 = [1.0,0.0,0.0,0.0,
        0.0,1.0,0.0,0.0,
        0.0,0.0,1.0,0.0,
        0.0,0.0,0.0,1.0]
  [[objects.shape]]
  type="obj"
  path="light.obj"

  [[objects.name]]
  name = "sphere"
  [[objects.material]]
  name = "matte_white"
  type = "dielectric"
  albedo = [1.0,1.0,1.0]
  ior = 1.5
  texture = "constant"
  [[objects.transform]]
  matrix4 = [1.0,0.0,0.0,228.0,
        0.0,1.0,0.0,223.0,
        0.0,0.0,1.0,200.0,
        0.0,0.0,0.0,1.0]
  [[objects.shape]]
  type="sphere"
  radius = 50.0

  [[objects.name]]
  name = "another_sphere"
  [[objects.material]]
  name = "cook_test"
  type = "cooktorrance"
  albedo = [0.3,0.3,0.1]
  roughness = 0.8
  metallic = 0.1
  f0 = [0.04,0.04,0.04]
  texture = "constant"
  [[objects.transform]]
  matrix4 = [1.0,0.0,0.0,378.0,
        0.0,1.0,0.0,53.0,
        0.0,0.0,1.0,150.0,
        0.0,0.0,0.0,1.0]
  [[objects.shape]]
  type="sphere"
  radius = 50.0
