# This is a basic workflow to help you get started with Actions

name: Windows-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Setup VS Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@master
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: configure
      env:
        CXX: cl
        CC: cl
      run: |
        mkdir build
        cd build
        pwd
        cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE -DDI_BUILD_TESTS=ON -DDI_BUILD_DEBUGGER=ON -DEXPERIMENTAL_UNITY_BUILD=ON ..
    - name: build
      run:  cmake --build build --parallel
    - name: run
      run: |
        cd build
        ./DiRender ../sample.toml
    - name: test
      run: |
        cd build
        ctest -T test --verbose
